//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPlanProduct
    {
        public int id { get; set; }
        public Nullable<int> id_plan { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<double> productCount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductionPlan ProductionPlan { get; set; }
    }
}
