//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductionPlanProducts = new HashSet<ProductionPlanProduct>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> id_productType { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> count { get; set; }
        public byte[] image { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionPlanProduct> ProductionPlanProducts { get; set; }
    }
}
